[package]
name = "bevy_3d_platformer_tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.2.1"
bevy = "0.15.3"
bevy-tnua = "0.22.0"
bevy-tnua-avian3d = "0.3.1"
bevy_gltf = "0.15.3"
bevy_panorbit_camera = "0.23.0"
bevy_skein = "0.1.2"
